config/routes.rb
Rails.application.routes.draw do
  resources :comics do
    resources :reviews
  end
  resources :applications

  root 'applications#index'

  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  has_many :application_comics
  has_many :comics, through: :application_comics
  accepts_nested_attributes_for :application_comics, allow_destroy: true

  mount_uploader :image, ImageUploader
end

app/models/application_comic.rb
class ApplicationComic < ApplicationRecord
  belongs_to :application
  belongs_to :comic
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord
  has_many :application_comics
  has_many :applications, through: :application_comics
  has_many :reviews
  accepts_nested_attributes_for :application_comics, allow_destroy: true

  mount_uploader :image, ImageUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :comic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def index
    @applications = Application.all
    @comics = Comic.all
    # require 'net/http'
    # require 'uri'
    # require 'json'
    #
    # uri = URI.parse('https://get.mobu.jp/api/ads/3.3/?pcode=manga-app&device=android')
    # json = Net::HTTP.get(uri)
    # option = JSON.parse(json)
    # maxpage = option['adSearch']['ads']['maxPage'].to_i
    #
    # @title = []
    #
    # for page in 1..1 do
    #   uri = URI.parse("https://get.mobu.jp/api/ads/3.3/?pcode=manga-app&device=android&page=#{page}")
    #   json = Net::HTTP.get(uri)
    #   result = JSON.parse(json)
    #   result = result['adSearch']['ads']['ad']
    #   # for i in 1..count-1 do
    #   #   tmp = result['adSearch']['ads']['ad'][i]['title']
    #   #   @title.push(tmp)
    #   #   tmp = result['adSearch']['ads']['ad'][i]['unit_price']
    #   #   @unit_price.push(tmp)
    #   # end
    #   result.each do |data|
    #     @title.push()
    #   end
    # end
  end
  def show
    @application = Application.find(params[:id])

    # @comics = Comic.includes(:applications).where(application_id: params[:id])
    @comics = Comic.includes(:applications).where(applications: {id: params[:id]}).page(params[:page])
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  def index
    @comics = Comic.all
  end

  def show
    @comic = Comic.find(params[:id])
    @applications = Application.includes(:comics).where(comics: {id: params[:id]})
    @reviews = Review.where(comic_id: params[:id]).order('created_at DESC')
    @staravg = Review.where(comic_id: params[:id]).average(:star)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.where(comic_id: @topic_id)
  end

  def new
    @comic = Comic.find(params[:comic_id])
    @review = Review.new
  end

  def create
    @comic = Comic.find(params[:comic_id])
    @review = Review.new(review_params)

    if @review.save
      redirect_to comic_path(params[:comic_id]), success: 'コメント投稿に成功しました'
    else
      flash.now[:danger] = 'コメント投稿に失敗しました'
      render :new
    end
  end

  private
  def review_params
    params.require(:review).permit(:star, :context).merge(comic_id: params[:comic_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/applications/index.html.erb
<div class="container">
    <p>当サイトは、漫画アプリで掲載されている漫画の一覧をまとめているウェブサイトです。現在、漫画：<%= @comics.count %>作品、マンガアプリ：<%= @applications.count %>つを掲載しています。</p>
      <div class="row">
        <% @applications.each do |application| %>
          <div class="col-md-4">
            <p><%= image_tag application.image.url , :size => "128x128" %></p>
            <p><%= link_to application.name , application_path(application.id) %></p>
            <%= link_to "iOSで読む", application.ioslink, class: 'btn btn-success' ,target: "_blank" %>
            <%= link_to "Androidで読む", application.androidlink, class: 'btn btn-success' ,target: "_blank" %>
          </div>
        <% end %>
      </div>
    <h2>新着作品</h2>
    <% @comics.each do |comic| %>

        <div class="col-md-3">
          <p><%= image_tag comic.image.url , :size => "128x128" %></p>
          <p><%= link_to comic.name , comic_path(comic.id) %></p>
          <% comic.applications.each do |f| %>
            <%= f.name %>
          <% end %>
        </div>
    <% end %>
</div>

app/views/applications/show.html.erb
<div class="container">
  <h2><%= @application.name %></h2>
  <%= link_to "iOSで読む", @application.ioslink, class: 'btn btn-default' ,target: "_blank" %>
  <%= link_to "Androidで読む", @application.androidlink, class: 'btn btn-default' ,target: "_blank" %>
  <h2><%= @application.name %>の作品一覧</h2>
    <div id="comics">
      <div class="page">
        <%= render @comics %>
      </div>
    </div>
    <%= paginate @comics , remote: true%>
</div>

app/views/applications/show.js.erb
$("#comics").append("<div class='page'><%= escape_javascript(render(@comics)) %></div>");

app/views/comics/_comic.html.erb
<div class="comic">
<div class="comic clearfix page-header">
  <div class="col-md-2">
    <p><%= image_tag comic.image.url , :size => "120x175"  %></p>
  </div>
  <div class="col-md-6">
    <p><%= link_to comic.name , comic_path(comic.id) %></p>
    <p>評価：<div class="rating" data-score="<%= comic.reviews.average(:star) %></p>"></div></p>
    <p><%= comic.overview %></p>
  </div>
</div>
</div>

<script>
$('.rating').raty({
  size      : 36,
  readOnly  : true,
  starOff   : '/assets/star-off.png',
  starOn    : '/assets/star-on.png',
  starHalf  : '/assets/star-half.png',
  number    : 5,
  score     : function(){
    return $(this).attr('data-score');
  }
});
</script>

app/views/comics/index.html.erb
<h2>マンガアプリで読める漫画一覧</h2>
<% @comics.each do |comic| %>
<p><%= link_to comic.name , comic_path(comic.id) %></p>
<% end %>

app/views/comics/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 clearfix">
    <h2><%= @comic.name %></h2>
    <div class="col-md-4">
      <p><%= image_tag @comic.image.url , :size => "350x500"  %></p>
      <p><%= link_to "レビューする",new_comic_review_path(comic_id: params[:id]) %></p>
      <p><div class="rating" data-score="<%= @staravg.to_s %>"></div></p>
    </div>
    <div class="col-md-6">
      <p>概要</p>
      <p><%= @comic.overview %></p>
    </div>
    </div>
    <h2><%= @comic.name %>が読める漫画アプリ</h2>
    <% @applications.each do |application| %>
    <div class="col-md-3">
      <p><%= image_tag application.image.url , :size => "128x128" %></p>
      <p><%= link_to application.name , application_path(application.id) %></p>
      <p><%= link_to "iOSで読む", application.ioslink, class: 'btn btn-default' ,target: "_blank" %></p>
      <p><%= link_to "Androidで読む", application.androidlink, class: 'btn btn-default' ,target: "_blank" %></p>
    </div>
    <% end %>
  </div>


  <h2><%= @comic.name %>のレビュー</h2>
  <% @reviews.each do |review| %>
    <div class="page-header">
      <p><div class="rating" data-score="<%= review.star.to_s %>"></div></p>
      <p><%= review.created_at.in_time_zone('Tokyo').strftime('%Y/%m/%d') %></p>
      <p><%= review.context %></p>
    </div>
  <% end %>
</div>


<script>
$('.rating').raty({
  size      : 36,
  readOnly  : true,
  starOff   : '/assets/star-off.png',
  starOn    : '/assets/star-on.png',
  starHalf  : '/assets/star-half.png',
  number    : 5,
  score     : function(){
    return $(this).attr('data-score');
  }
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MangaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= link_to "マンガアプリ検索LABO", root_path %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   root_path %></li>
        </ul>
      </nav>
    </div>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="comments-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h2 class="text-center text-white"><%= @comic.name %>のレビュー</h2>
        <div class="field" id="test"></div>
        <%= form_for [@comic,@review] do |f| %>
        <div class="star"></div>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <div class="field" id="star">
              <%= f.label :star %>
              <%= f.hidden_field :star, id: :review_star %>
            </div>
            <%= f.text_area :context, class: 'form-control' %>
          </div>
          <div class="">
          <%= f.submit "コメントする", class: 'btn-block btn-black' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
$('#star').raty({
  size      : 36,
  starOff   : '/assets/star-off.png',
  starOn    : '/assets/star-on.png',
  scoreName : 'review[star]'
});
</script>